spring:
  r2dbc:
#    URL ?????? ?????????? ? r2dbc, ? ?? "jdbc" ??? ??????
    url: r2dbc:postgresql://localhost:5432/postgres?schema=users
    username: root
    password: root

logging:
  level:
    org:
      springframework:
        r2dbc: debug

# ?????? ?? ????? ???????? ???? ?????????? ??? ????????? ? ?????????. ????? ???????? ???
#  ????? ????? ????????? ?????? ? ?????????????? ?????????? URL...?trace=true
# ?? ???????? ? ????????? ????????? ??? ?????????????? ?????????
server:
  error:
    include-stacktrace: ON_PARAM